<ul class="navbar-nav">

<!-- This is the label template -->
    <!-- <div class="icon icon-shape icon-sm shadow border-radius-md bg-white text-center me-2 d-flex align-items-center justify-content-center">
        <i class="fa fa-home"></i>
    </div>
    <span class="nav-link-text ms-1">Dashboard</span> -->
    <?php


    foreach ($this->container as $page) :
        /** @var Laminas\Navigation\Page\AbstractPage $page */

    ?>

        <li class="nav-item">
            <a class="nav-link  active" href="<?= $page->getHref() ?>">

                <?php echo $child->getLabel() ?>
            </a>
        </li>
        
    <?php endforeach; ?>
</ul>