<?php

/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */

use Application\Service\ApplicationService;
use Laminas\View\Helper\BasePath;

?>
<?= $this->doctype() ?>
<html lang="en">

<head>
    <meta charset="utf-8">
    <?= $this->headTitle(ApplicationService::APP_NAME)->setSeparator(' - ')->setAutoEscape(false) ?>

    <!-- Font Awesome Icons -->
    <script src="https://kit.fontawesome.com/42d5adcbca.js" crossorigin="anonymous"></script>
    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?= $this->headLink([
        'rel' => 'shortcut icon',
        'type' => 'image/vnd.microsoft.icon',
        'href' => $this->basePath() . '/img/favicon.ico'
    ])
        ->prependStylesheet($this->basePath("soft/assets/css/soft-ui-dashboard.css?v=1.0.6"))
        ->prependStylesheet($this->basePath("soft/assets/css/nucleo-svg.css"))
        ->prependStylesheet($this->basePath("soft/assets/css/nucleo-svg.css"))
        ->prependStylesheet($this->basePath("soft/assets/css/nucleo-icons.css"))
        ->prependStylesheet("https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700")

    ?>

    <!-- Scripts -->
    <?= $this->headScript() ?>
</head>

<body class="g-sidenav-show  bg-gray-100 virtual-reality">
    <style>
        @import url("https://fonts.googleapis.com/css2?family=Poppins:wght@700&display=swap" rel="stylesheet");

        @import url("https://fonts.googleapis.com/css?family=Montserrat:400,500,600,700");

        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        body {
            overflow: hidden;
            background-color: #f4f6ff;
        }

        .container {
            width: 100vw;
            height: 100vh;
            display: flex;
            justify-content: center;
            align-items: center;
            font-family: "Poppins", sans-serif;
            position: relative;
            left: 6vmin;
            text-align: center;
        }

        .cog-wheel1,
        .cog-wheel2 {
            transform: scale(0.7);
        }

        .cog1,
        .cog2 {
            width: 40vmin;
            height: 40vmin;
            border-radius: 50%;
            border: 6vmin solid #f3c623;
            position: relative;
        }


        .cog2 {
            border: 6vmin solid #4f8a8b;
        }

        .top,
        .down,
        .left,
        .right,
        .left-top,
        .left-down,
        .right-top,
        .right-down {
            width: 10vmin;
            height: 10vmin;
            background-color: #f3c623;
            position: absolute;
        }

        .cog2 .top,
        .cog2 .down,
        .cog2 .left,
        .cog2 .right,
        .cog2 .left-top,
        .cog2 .left-down,
        .cog2 .right-top,
        .cog2 .right-down {
            background-color: #4f8a8b;
        }

        .top {
            top: -14vmin;
            left: 9vmin;
        }

        .down {
            bottom: -14vmin;
            left: 9vmin;
        }

        .left {
            left: -14vmin;
            top: 9vmin;
        }

        .right {
            right: -14vmin;
            top: 9vmin;
        }

        .left-top {
            transform: rotateZ(-45deg);
            left: -8vmin;
            top: -8vmin;
        }

        .left-down {
            transform: rotateZ(45deg);
            left: -8vmin;
            top: 25vmin;
        }

        .right-top {
            transform: rotateZ(45deg);
            right: -8vmin;
            top: -8vmin;
        }

        .right-down {
            transform: rotateZ(-45deg);
            right: -8vmin;
            top: 25vmin;
        }

        .cog2 {
            position: relative;
            left: -10.2vmin;
            bottom: 10vmin;
        }

        h1 {
            color: #142833;
        }

        .first-four {
            position: relative;
            left: 6vmin;
            font-size: 40vmin;
        }

        .second-four {
            position: relative;
            right: 18vmin;
            z-index: -1;
            font-size: 40vmin;
        }

        .wrong-para {
            font-family: "Montserrat", sans-serif;
            position: absolute;
            bottom: 15vmin;
            padding: 3vmin 12vmin 3vmin 3vmin;
            font-weight: 600;
            color: #092532;
        }
    </style>
    <div>
        <!-- Navbar -->

        <!-- End Navbar -->
    </div>
    <div class="border-radius-xl mt-3 mx-3 position-relative" style="background-image: url('/assets/img/vr-bg.jpg') ; background-size: cover;">

        <main class="main-content mt-1 border-radius-lg">
            <div class="section min-vh-85 position-relative transform-scale-0 transform-scale-md-7">
                <div class="container">
                    <div class="row pt-10">
                        <div class="col-lg-1 col-md-1 pt-5 pt-lg-0 ms-lg-5 text-center">
                            <a href="javascript:;" class="avatar avatar-md border-0" data-bs-toggle="tooltip" data-bs-placement="left" title="My Profile">

                            </a>
                            <button class="btn btn-white border-radius-lg p-2 mt-2" type="button" data-bs-toggle="tooltip" data-bs-placement="left" title="Home">
                                <i class="fas fa-home p-2"></i>
                            </button>
                            <button class="btn btn-white border-radius-lg p-2" type="button" data-bs-toggle="tooltip" data-bs-placement="left" title="Search">
                                <i class="fas fa-search p-2"></i>
                            </button>
                            <button class="btn btn-white border-radius-lg p-2" type="button" data-bs-toggle="tooltip" data-bs-placement="left" title="Minimize">
                                <i class="fas fa-ellipsis-h p-2"></i>
                            </button>
                        </div>
                        <div class="col-lg-8 col-md-11">
                            <div class="d-flex">
                                <div class="me-auto">
                                    <div class="container">
                                        <h1 class="first-four">4</h1>
                                        <div class="cog-wheel1">
                                            <div class="cog1">
                                                <div class="top"></div>
                                                <div class="down"></div>
                                                <div class="left-top"></div>
                                                <div class="left-down"></div>
                                                <div class="right-top"></div>
                                                <div class="right-down"></div>
                                                <div class="left"></div>
                                                <div class="right"></div>
                                            </div>
                                        </div>

                                        <div class="cog-wheel2">
                                            <div class="cog2">
                                                <div class="top"></div>
                                                <div class="down"></div>
                                                <div class="left-top"></div>
                                                <div class="left-down"></div>
                                                <div class="right-top"></div>
                                                <div class="right-down"></div>
                                                <div class="left"></div>
                                                <div class="right"></div>
                                            </div>
                                        </div>
                                        <h1 class="second-four">4</h1>
                                        <p class="wrong-para">Uh Oh! Page not found!</p>
                                    </div>Ï

                                </div>

                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </main>
    </div>
    <footer class="footer pt-3  ">
        <div class="container-fluid">
            <div class="row align-items-center justify-content-lg-between">
                <div class="col-lg-6 mb-lg-0 mb-4">
                    <div class="copyright text-center text-sm text-muted text-lg-start">
                        © <script>
                            document.write(new Date().getFullYear())
                        </script>,
                        made with <i class="fa fa-heart"></i> by
                        <a href="https://www.creative-tim.com" class="font-weight-bold" target="_blank">Creative Tim</a>
                        for a better web.
                    </div>
                </div>
                <div class="col-lg-6">
                    <ul class="nav nav-footer justify-content-center justify-content-lg-end">
                        <li class="nav-item">
                            <a href="https://www.creative-tim.com" class="nav-link text-muted" target="_blank">Creative Tim</a>
                        </li>
                        <li class="nav-item">
                            <a href="https://www.creative-tim.com/presentation" class="nav-link text-muted" target="_blank">About Us</a>
                        </li>
                        <li class="nav-item">
                            <a href="https://www.creative-tim.com/blog" class="nav-link text-muted" target="_blank">Blog</a>
                        </li>
                        <li class="nav-item">
                            <a href="https://www.creative-tim.com/license" class="nav-link pe-0 text-muted" target="_blank">License</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </footer>

    <!--   Core JS Files   -->
    <script src="/assets/js/core/popper.min.js"></script>
    <script src="/assets/js/core/bootstrap.min.js"></script>
    <script src="/assets/js/plugins/perfect-scrollbar.min.js"></script>
    <script src="/assets/js/plugins/smooth-scrollbar.min.js"></script>
    <script>
        let t1 = gsap.timeline();
        let t2 = gsap.timeline();
        let t3 = gsap.timeline();

        t1.to(".cog1", {
            transformOrigin: "50% 50%",
            rotation: "+=360",
            repeat: -1,
            ease: Linear.easeNone,
            duration: 8
        });

        t2.to(".cog2", {
            transformOrigin: "50% 50%",
            rotation: "-=360",
            repeat: -1,
            ease: Linear.easeNone,
            duration: 8
        });

        t3.fromTo(".wrong-para", {
            opacity: 0
        }, {
            opacity: 1,
            duration: 1,
            stagger: {
                repeat: -1,
                yoyo: true
            }
        });

        var win = navigator.platform.indexOf('Win') > -1;
        if (win && document.querySelector('#sidenav-scrollbar')) {
            var options = {
                damping: '0.5'
            }
            Scrollbar.init(document.querySelector('#sidenav-scrollbar'), options);
        }
    </script>
    <!-- Github buttons -->
    <script async defer src="https://buttons.github.io/buttons.js"></script>
    <!-- Control Center for Soft Dashboard: parallax effects, scripts for the example pages etc -->
    <script src="/assets/js/soft-ui-dashboard.min.js?v=1.0.7"></script>
</body>

<!-- <body>
    <nav class="navbar navbar-expand-md navbar-dark mb-4" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <a class="navbar-brand" href="<?= $this->url('home') ?>">
                    <img src="<?= $this->basePath('img/laminas-logo.svg') ?>" alt="Laminas">MVC Skeleton
                </a>
            </div>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav">
                    <li class="nav-item active">
                        <a class="nav-link" href="<?= $this->url('home') ?>">
                            Home <span class="sr-only">(current)</span>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container">
        <?= $this->content ?>
        <hr>
        <footer>
            <p>
                &copy; <?= date('Y') ?>
                <a href="https://getlaminas.org/">Laminas Project</a> a Series of LF Projects, LLC.
            </p>
        </footer>
    </div>
    <?= $this->inlineScript()
        ->prependFile($this->basePath('js/bootstrap.min.js'))
        ->prependFile($this->basePath('js/jquery-3.5.1.min.js')) ?>
</body> -->

</html>